version: '3'
services:

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    links:
      - redis:redis
  test-service:
    build: ./test-service
    ports:
      - "8081:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"