version: '3'
services:
  api-gateway:
    build: ./api-gateway
    environment:
      authService: auth-service
      beerService: beer-service
    ports:
      - "3000:3000"
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    links:
      - redis:redis
  beer-service:
    build: ./beer-service
    ports:
      - "8082:8082"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  frontend:
    build: frontend
    ports:
      - "4200:4200"
