version: '3'
services:
  api-gateway:
    image: zwirek009/rsoproject_api-gateway:latest
    build: ./api-gateway
    environment:
      authService: auth-service
      beerService: beer-service
    ports:
      - "3000:3000"
  auth-service:
    image: zwirek009/rsoproject_auth-service:latest
    build: ./auth-service
  beer-service:
    image: zwirek009/rsoproject_beer-service:latest
    build: ./beer-service
  redis:
    image: "redis:alpine"
  frontend:
    image: zwirek009/rsoproject_frontend:latest
    build: frontend
    ports:
      - "4200:4200"
    links: 
      - api-gateway:api-gateway
    depends_on:
      - api-gateway
