version: '3'
services:
  api-gateway:
    image: 127.0.0.1:5000/api-gateway
    environment:
      authService: auth-service
      beerService: beer-service
    ports:
      - "3000:3000"
  auth-service:
    image: 127.0.0.1:5000/auth-service
    ports:
      - "8080:8080"
    links:
      - redis:redis
  beer-service:
    image: 127.0.0.1:5000/beer-service
    ports:
      - "8082:8082"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  frontend:
    image: 127.0.0.1:5000/frontend
    ports:
      - "4200:4200"
networks:
  webnet:
  
