version: '3'
services:
  api-gateway:
    image: zwirek009/rsoproject_api-gateway:latest
    environment:
      authService: auth-service
      beerService: beer-service
    ports:
      - "3000:3000"
  auth-service:
    image: zwirek009/rsoproject_auth-service:latest
  beer-service:
    image: zwirek009/rsoproject_beer-service:latest
  redis:
    image: "redis:alpine"
  frontend:
    image: zwirek009/rsoproject_frontend:latest
    deploy:
      replicas: 5
